//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvaluacionMVC.Models
{
    using System;
    using System.Collections.Generic;
    [System.ComponentModel.DataAnnotations.MetadataType(typeof(Producto_Validar))]
    public partial class producto
    {
        public int idProducto { get; set; }
        public string Nombre { get; set; }
        public string idCategoria { get; set; }
        public Nullable<int> precio { get; set; }
        public Nullable<System.DateTime> fVencimiento { get; set; }
        public Nullable<int> unidades { get; set; }
    
        public virtual categoria categoria { get; set; }
    }
}
